service: aws-python # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

functions:
  simpleupload:
    handler: handler.simpleupload
    timeout: 300
