service: aws-python # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:invoke"
      Resource: "*"

functions:
  simpleupload:
    handler: handler.simpleupload
    timeout: 30

  multipartupload:
    handler: handler.multipartupload
    timeout: 30

  multipart_upload_web_s3_part:
    handler: handler.multipart_upload_web_s3_part_lambda
    timeout: 30
